### PR TITLE
Updated template to latest versions of everything

### PR DESCRIPTION
**Pull request by OndrejValenta**
npm run build builds the template just super green
cordova add platform android / cordova run android is also ok
phonegap build ok as well

Android Simulator result here:
image

### CODE REVIEW

**Comment by devgeeks** [comment]
Is there a reason why there are also so any formatting/stylistic changes (indentation, semicolons, etc) as well as removing some of the linting?

**Comment by OndrejValenta** [comment]
Is there? I just replaced whole lines in package.json and replaced all text in build configuration scripts. I think that's the reason. I took the configuration scripts from existing vuejs projects based on vue-cli and did not touch them at all, just copy-paste them.

**Comment by OndrejValenta** [comment]
So according to this https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5
The lock file is supposed to be commited and that's what made so many changes

**Comment by devgeeks** [comment]
Thanks so much for this, but since i took so long to follow up, this has gotten out of sync. :(

I'll update everything in a new PR very soon.

**Comment by OndrejValenta** [comment]
No problem.. :-)

**Pull request closed without merging**
